

server.port=8085

# Student Service
spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=lb://STUDENT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**,/api/auth/**,/api/courses/**

# Attendance Service
spring.cloud.gateway.routes[1].id=attendance-service
spring.cloud.gateway.routes[1].uri=lb://ATTENDANCE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/attendance/**

# Result Service
spring.cloud.gateway.routes[2].id=result-service
spring.cloud.gateway.routes[2].uri=lb://RESULT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/results/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.appname=API-GATEWAY
